#!/bin/sh
. /etc/arch.sh
local lic_inv=$(nvram get license_invalid)
case "$ACTION" in
        add)
            PROD_CAT=$(nvram get prod_cat)
            [ "$PROD_CAT" != "M" -a "$PROD_CAT" != "N" -a \
              "$PROD_CAT" != "P" -a "$PROD_CAT" != "U" -a \
              "$PROD_CAT" != "I" -a "$PROD_CAT" != "A" -a \
              "$PROD_CAT" != "W" ] && exit

            local count=0
            WAN_NUM=$(nvram get wan_num)
            for i in $(seq 0 $WAN_NUM)
            do
                [ "$(nvram get wan${i}_proto)" = "wwan" -o "$(nvram get wan${i}_proto)" = "directip"  ] && [ -n "$(nvram get wan${i}_ipaddr)" ] && {
                count=$(($count+1))
            }
            done          
            [ $count -eq 0 ] && {
                arch_led_start wwan
            }
            lock /tmp/.ezpcom-mode
            EZPHOTPLUG=scsi_generic /usr/sbin/ezpcom-mode
            lock -u /tmp/.ezpcom-mode
            ;;
        remove)
            arch_led_start remove
            sleep 5
            arch_led_stop remove
            ;;
esac

